// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autochat.proto

package server;

public final class Autochat {
  private Autochat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_AutoChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_AutoChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_AutoChatReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_AutoChatReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016autochat.proto\022\006server\"#\n\017AutoChatRequ" +
      "est\022\020\n\010question\030\001 \001(\t\"!\n\rAutoChatReply\022\020" +
      "\n\010response\030\001 \001(\t2H\n\010AutoChat\022<\n\010autoChat" +
      "\022\027.server.AutoChatRequest\032\025.server.AutoC" +
      "hatReply\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_AutoChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_AutoChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_AutoChatRequest_descriptor,
        new java.lang.String[] { "Question", });
    internal_static_server_AutoChatReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_AutoChatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_AutoChatReply_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
