// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autochat.proto

package server;

public interface AutoChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.AutoChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string question = 1;</code>
   * @return The question.
   */
  java.lang.String getQuestion();
  /**
   * <code>string question = 1;</code>
   * @return The bytes for question.
   */
  com.google.protobuf.ByteString
      getQuestionBytes();
}
